const ADD_INGREDIENT = "ADD_INGREDIENT";
const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
const SET_INGREDIENTS = "SET_INGREDIENTS";
const FETCH_INGREDIENTS_FAILED = "FETCH_INGREDIENTS_FAILED";
const FETCH_ORDERS_INIT = "FETCH_ORDERS_INIT";
const FETCH_ORDERS_START = "FETCH_ORDERS_START";
const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
const FETCH_ORDERS_FAIL = "FETCH_ORDERS_FAIL";
const PURCHASE_BURGER_START = "PURCHASE_BURGER_START";
const PURCHASE_BURGER_SUCCESS = "PURCHASE_BURGER_SUCCESS";
const PURCHASE_BURGER_FAIL = "PURCHASE_BURGER_FAIL";
const PURCHASE_INIT = "PURCHASE_INIT";

const AUTH_START = "AUTH_START";
const AUTH_SUCCESS = "AUTH_SUCCESS";
const AUTH_FAIL = "AUTH_FAIL";
const AUTH_LOGOUT = "AUTH_LOGOUT";
const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";

export {
  ADD_INGREDIENT,
  REMOVE_INGREDIENT,
  SET_INGREDIENTS,
  FETCH_INGREDIENTS_FAILED,
  FETCH_ORDERS_INIT,
  FETCH_ORDERS_START,
  FETCH_ORDERS_SUCCESS,
  FETCH_ORDERS_FAIL,
  PURCHASE_BURGER_START,
  PURCHASE_BURGER_SUCCESS,
  PURCHASE_BURGER_FAIL,
  PURCHASE_INIT,
  AUTH_START,
  AUTH_SUCCESS,
  AUTH_FAIL,
  AUTH_LOGOUT,
  SET_AUTH_REDIRECT_PATH,
};
